spring:
  datasource:
    url: jdbc:mysql://192.168.15.129:3306/study?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: password
  jpa:
    show-sql: true
    generate-ddl: true
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
  hibernate:
    ddl-auto: update

erupt-app:
  # 登录失败几次出现验证码，值为0时表示一直需要登录验证码
  verify-code-count: 2
erupt:
  upms:
    # 登录session时长（redisSession为true时有效）
    expireTimeByLogin: 60
    # 严格的角色菜单策略，如果非管理员用户拥有“角色管理权限”则仅能编辑已有权限的角色菜单
    # 1.10.6 及以上版本支持
    strictRoleMenuLegal: true
  # 开启redis方式存储session，默认false，开启后需在配置文件中添加redis配置（同 Spring Boot）
  redisSession: false
  # redis session是否自动续期，1.10.8及以上版本支持
  redisSessionRefresh: false
  # 附件上传存储路径, 默认路径为：/opt/erupt-attachment
  uploadPath: E:/erupt/pictures
  # 是否保留上传文件原始名称
  keepUploadFileName: false
  # 是否记录操作日志，默认true，该功能开启后可在【系统管理 → 操作日志】中查看操作日志
  security.recordOperateLog: true

